"""initial migration

Revision ID: 10bc03410ec2
Revises: 
Create Date: 2025-09-26 16:56:42.261811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '10bc03410ec2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_note_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.Column('source_content', sa.JSON(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_notes_source_note_id'), 'source_notes', ['source_note_id'], unique=True)
    op.add_column('qa_pairs', sa.Column('card_type', sa.String(), nullable=True, server_default='qa'))
    op.add_column('qa_pairs', sa.Column('source_note_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_qa_pairs_card_type'), 'qa_pairs', ['card_type'], unique=False)
    op.create_foreign_key(None, 'qa_pairs', 'source_notes', ['source_note_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qa_pairs', type_='foreignkey')
    op.drop_index(op.f('ix_qa_pairs_card_type'), table_name='qa_pairs')
    op.drop_column('qa_pairs', 'source_note_id')
    op.drop_column('qa_pairs', 'card_type')
    op.drop_index(op.f('ix_source_notes_source_note_id'), table_name='source_notes')
    op.drop_table('source_notes')
    # ### end Alembic commands ###
